# Generated by Django 3.2.14 on 2022-07-18 20:49

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('payment_option', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1)),
                ('customer', models.ForeignKey(on_delete=models.SET(core.models.get_unknown_customer), to='core.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
